services:
  app:
    build:
      context: ./app
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mydb
    depends_on:
      - postgres
      #- mysql
      #- payload
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql_db
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=rootpassword
  #     - MYSQL_DATABASE=mydb
  #     - MYSQL_USER=app_user
  #     - MYSQL_PASSWORD=password
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql
  #   networks:
  #     - app-network

  payload:
    build:
      context: ./payloadcms
    container_name: payload_cms
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mydb
      - PAYLOAD_SECRET=your_payload_secret_here
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
